export const buckets = [
  {
    id: "viide",
    label: "Alustuseks",
    memberIds: [
      "arvo-part",
      "lennart-meri",
      "carmen-kass",
      "ott-tanak",
      "tommy-cash",
      "kerli",
      "kersti-kaljulaid",
      "kimi-raikkonen",
      "elon-musk",
      "jouluvana",
      "typical-american",
      "latvian-neighbour",
    ],
  },
  {
    id: "siin-kuulsad",
    label: "Kohalikud kuulsused",
    memberIds: [
      "george-w-bush",
      "dave-benton",
      "cheburashka",
      "pipi-pikksukk",
      "mart-avandi",
      "ott-sepp",
      "edgar-savisaar",
      "anu-saagim",
      "baruto",
      "nublu",
      "5miinust",
    ],
  },
  {
    id: "presidendid",
    label: "Eesti presidendid",
    memberIds: [
      "konstantin-pats",
      "lennart-meri",
      "arnold-ruutel",
      "toomas-hendrik-ilves",
      "kersti-kaljulaid",
      "alar-karis",
    ],
  },
  {
    id: "eurovisioon",
    label: "Eurovisioon",
    memberIds: [
      "tommy-cash",
      "koit-toome",
      "loreen",
      "lordi",
      "conchita-wurst",
      "verka-serduchka",
      "celine-dion",
      "tanel-padar",
      "dave-benton",
    ],
  },
  {
    id: "hollywood",
    label: "Hollywood",
    memberIds: [
      "brad-pitt",
      "scarlett-johansson",
      "adam-driver",
      "cate-blanchett",
      "keanu-reeves",
      "margot-robbie",
      "christopher-walken",
      "christopher-nolan",
      "robert-pattinson",
      "mads-mikkelsen",
    ],
  },
  {
    id: "juhid",
    label: "Maailma juhid",
    memberIds: [
      "donald-trump",
      "angela-merkel",
      "alexander-stubb",
      "volodymyr-zelenskyy",
      "emmanuel-macron",
      "sanna-marin",
      "xi-jinping",
      "kaja-kallas",
      "joe-biden",
      "barack-obama",
      "george-w-bush",
    ],
  },
  {
    id: "kangelased",
    label: "Superkangelased",
    memberIds: [
      "superman",
      "batman",
      "elsa",
      "thor",
      "spider-man",
      "captain-america",
      "lotte",
      "kalevipoeg",
      "muumitroll",
    ],
  },
  {
    id: "kirjanikud",
    label: "Kirjanikud",
    memberIds: [
      "tammsaare",
      "jaan-kross",
      "andrus-kivirahk",
      "sofi-oksanen",
      "tolstoy",
      "hemingway",
      "kafka",
    ],
  },
];

