// Display: SPF 50 / ei ütle tere tänaval / käib saunas.
// Scores from pairwise (2026-08-16). High = named pole. juured in data only.
export const people = [
  {
    id: "arvo-part",
    name: "Arvo Pärt",
    valimus: 0.93,
    temperament: 0.93,
    kultuur: 0.97,
    juured: 0.97,
    portrait: "portraits/arvo-part.jpg",
    note: "Isegi muusika oli vaikne",
  },
  {
    id: "lennart-meri",
    name: "Lennart Meri",
    valimus: 0.84,
    temperament: 0.49,
    kultuur: 0.89,
    juured: 0.95,
    portrait: "portraits/lennart-meri.jpg",
  },
  {
    id: "carmen-kass",
    name: "Carmen Kass",
    valimus: 1,
    temperament: 0.78,
    kultuur: 0.73,
    juured: 0.91,
    portrait: "portraits/carmen-kass.jpg",
    note: "Paide nägu, Milano valgus.",
  },
  {
    id: "ott-tanak",
    name: "Ott Tänak",
    valimus: 0.96,
    temperament: 0.99,
    kultuur: 0.77,
    juured: 0.94,
    portrait: "portraits/ott-tanak.jpg",
    note: "Sõnad otsas, gaas põhjas.",
  },
  {
    id: "tommy-cash",
    name: "Tommy Cash",
    valimus: 0.74,
    temperament: 0.42,
    kultuur: 0.81,
    juured: 0.76,
    portrait: "portraits/tommy-cash.jpg",
  },
  {
    id: "kerli",
    name: "Kerli",
    valimus: 0.95,
    temperament: 0.54,
    kultuur: 0.72,
    juured: 0.89,
    portrait: "portraits/kerli.jpg",
    note: "Metshaldjas",
  },
  {
    id: "kersti-kaljulaid",
    name: "Kersti Kaljulaid",
    valimus: 0.97,
    temperament: 0.5,
    kultuur: 0.69,
    juured: 0.93,
    portrait: "portraits/kersti-kaljulaid.jpg",
    note: "EU-CV",
  },
  {
    id: "kimi-raikkonen",
    name: "Kimi Räikkönen",
    valimus: 0.64,
    temperament: 1,
    kultuur: 0.55,
    juured: 0.09,
    portrait: "portraits/kimi-raikkonen.jpg",
    note: "Bwoah",
  },
  {
    id: "elon-musk",
    name: "Elon Musk",
    valimus: 0.42,
    temperament: 0.53,
    kultuur: 0.04,
    juured: 0.03,
    portrait: "portraits/elon-musk.jpg",
    note: "Marsimees",
  },
  {
    id: "jouluvana",
    name: "Jõuluvana",
    valimus: 0.5,
    temperament: 0.38,
    kultuur: 0.64,
    juured: 0.14,
    portrait: "portraits/jouluvana.jpg",
  },
  {
    id: "typical-american",
    name: "Keskmine Ameeriklane",
    valimus: 0.22,
    temperament: 0.14,
    kultuur: 0,
    juured: 0.01,
    portrait: "portraits/typical-american.jpg",
    note: "“Is Estonia in Eastern Europe?”",
  },
  {
    id: "latvian-neighbour",
    name: "Lätlane",
    valimus: 0.8,
    temperament: 0.66,
    kultuur: 0.57,
    juured: 0.33,
    portrait: "portraits/latvian-neighbour.jpg",
  },
  {
    id: "konstantin-pats",
    name: "Konstantin Päts",
    valimus: 0.82,
    temperament: 0.84,
    kultuur: 0.88,
    juured: 0.97,
    portrait: "portraits/konstantin-pats.jpg",
    note: "Vaikiv ajastu",
  },
  {
    id: "arnold-ruutel",
    name: "Arnold Rüütel",
    valimus: 0.81,
    temperament: 0.91,
    kultuur: 0.86,
    juured: 0.96,
    portrait: "portraits/arnold-ruutel.jpg",
    note: "palju õnne ja tahet jätkuvalt edaspidiseks!",
  },
  {
    id: "toomas-hendrik-ilves",
    name: "Toomas Hendrik Ilves",
    valimus: 0.7,
    temperament: 0.47,
    kultuur: 0.7,
    juured: 0.76,
    portrait: "portraits/toomas-hendrik-ilves.jpg",
    note: "Soome DJ",
  },
  {
    id: "alar-karis",
    name: "Alar Karis",
    valimus: 0.92,
    temperament: 0.89,
    kultuur: 0.85,
    juured: 0.93,
    portrait: "portraits/alar-karis.jpg",
  },
  {
    id: "koit-toome",
    name: "Koit Toome",
    valimus: 0.88,
    temperament: 0.41,
    kultuur: 0.74,
    juured: 0.9,
    portrait: "portraits/koit-toome.jpg",
  },
  {
    id: "loreen",
    name: "Loreen",
    valimus: 0.26,
    temperament: 0.57,
    kultuur: 0.38,
    juured: 0.03,
    portrait: "portraits/loreen.jpg",
    note: "Euphoria",
  },
  {
    id: "lordi",
    name: "Lordi",
    valimus: 0.04,
    temperament: 0.16,
    kultuur: 0.54,
    juured: 0.1,
    portrait: "portraits/lordi.jpg",
    note: "Hard Rock Hallelujah",
  },
  {
    id: "conchita-wurst",
    name: "Conchita Wurst",
    valimus: 0.24,
    temperament: 0.15,
    kultuur: 0.35,
    juured: 0.01,
    portrait: "portraits/conchita-wurst.jpg",
    note: "Habe",
  },
  {
    id: "verka-serduchka",
    name: "Verka Serduchka",
    valimus: 0.23,
    temperament: 0.01,
    kultuur: 0.36,
    juured: 0.04,
    portrait: "portraits/verka-serduchka.jpg",
    note: "Lasha Tumbai",
  },
  {
    id: "celine-dion",
    name: "Céline Dion",
    valimus: 0.31,
    temperament: 0.03,
    kultuur: 0.24,
    juured: 0.01,
    portrait: "portraits/celine-dion.jpg",
    note: "My heart will go on",
  },
  {
    id: "brad-pitt",
    name: "Brad Pitt",
    valimus: 0.51,
    temperament: 0.46,
    kultuur: 0.14,
    juured: 0.03,
    portrait: "portraits/brad-pitt.jpg",
  },
  {
    id: "scarlett-johansson",
    name: "Scarlett Johansson",
    valimus: 0.54,
    temperament: 0.62,
    kultuur: 0.16,
    juured: 0.09,
    portrait: "portraits/scarlett-johansson.jpg",
  },
  {
    id: "adam-driver",
    name: "Adam Driver",
    valimus: 0.49,
    temperament: 0.74,
    kultuur: 0.43,
    juured: 0.02,
    portrait: "portraits/adam-driver.jpg",
  },
  {
    id: "cate-blanchett",
    name: "Cate Blanchett",
    valimus: 0.55,
    temperament: 0.64,
    kultuur: 0.2,
    juured: 0.02,
    portrait: "portraits/cate-blanchett.jpg",
  },
  {
    id: "keanu-reeves",
    name: "Keanu Reeves",
    valimus: 0.32,
    temperament: 0.81,
    kultuur: 0.19,
    juured: 0.02,
    portrait: "portraits/keanu-reeves.jpg",
  },
  {
    id: "margot-robbie",
    name: "Margot Robbie",
    valimus: 0.34,
    temperament: 0.45,
    kultuur: 0.15,
    juured: 0.01,
    portrait: "portraits/margot-robbie.jpg",
  },
  {
    id: "christopher-walken",
    name: "Christopher Walken",
    valimus: 0.46,
    temperament: 0.69,
    kultuur: 0.18,
    juured: 0.02,
    portrait: "portraits/christopher-walken.jpg",
  },
  {
    id: "donald-trump",
    name: "Donald Trump",
    valimus: 0.36,
    temperament: 0,
    kultuur: 0.03,
    juured: 0.01,
    portrait: "portraits/donald-trump.jpg",
    note: "you're fired",
  },
  {
    id: "angela-merkel",
    name: "Angela Merkel",
    valimus: 0.57,
    temperament: 0.88,
    kultuur: 0.5,
    juured: 0.04,
    portrait: "portraits/angela-merkel.jpg",
    note: "wir schaffen das",
  },
  {
    id: "alexander-stubb",
    name: "Alexander Stubb",
    valimus: 0.61,
    temperament: 0.31,
    kultuur: 0.53,
    juured: 0.11,
    portrait: "portraits/alexander-stubb.jpg",
  },
  {
    id: "volodymyr-zelenskyy",
    name: "Volodymyr Zelenskyy",
    valimus: 0.27,
    temperament: 0.24,
    kultuur: 0.32,
    juured: 0.05,
    portrait: "portraits/volodymyr-zelenskyy.jpg",
    note: "Rahva teener",
  },
  {
    id: "emmanuel-macron",
    name: "Emmanuel Macron",
    valimus: 0.3,
    temperament: 0.26,
    kultuur: 0.3,
    juured: 0.01,
    portrait: "portraits/emmanuel-macron.jpg",
    note: "Jupiter en même temps",
  },
  {
    id: "sanna-marin",
    name: "Sanna Marin",
    valimus: 0.62,
    temperament: 0.32,
    kultuur: 0.51,
    juured: 0.1,
    portrait: "portraits/sanna-marin.jpg",
  },
  {
    id: "xi-jinping",
    name: "Xi Jinping",
    valimus: 0.08,
    temperament: 0.8,
    kultuur: 0.01,
    juured: 0,
    portrait: "portraits/xi-jinping.jpg",
  },
  {
    id: "superman",
    name: "Superman",
    valimus: 0.14,
    temperament: 0.22,
    kultuur: 0.07,
    juured: 0.01,
    portrait: "portraits/superman.jpg",
  },
  {
    id: "batman",
    name: "Batman",
    valimus: 0.07,
    temperament: 0.97,
    kultuur: 0.09,
    juured: 0.01,
    portrait: "portraits/batman.jpg",
  },
  {
    id: "elsa",
    name: "Elsa",
    valimus: 0.59,
    temperament: 0.55,
    kultuur: 0.11,
    juured: 0.08,
    portrait: "portraits/elsa.jpg",
  },
  {
    id: "thor",
    name: "Thor",
    valimus: 0.45,
    temperament: 0.18,
    kultuur: 0.12,
    juured: 0.12,
    portrait: "portraits/thor.jpg",
  },
  {
    id: "spider-man",
    name: "Spider-Man",
    valimus: 0.05,
    temperament: 0.19,
    kultuur: 0.08,
    juured: 0.01,
    portrait: "portraits/spider-man.jpg",
  },
  {
    id: "captain-america",
    name: "Captain America",
    valimus: 0.12,
    temperament: 0.23,
    kultuur: 0.05,
    juured: 0.01,
    portrait: "portraits/captain-america.jpg",
  },
  {
    id: "tammsaare",
    name: "A. H. Tammsaare",
    valimus: 0.78,
    temperament: 0.95,
    kultuur: 1,
    juured: 0.97,
    portrait: "portraits/tammsaare.jpg",
  },
  {
    id: "jaan-kross",
    name: "Jaan Kross",
    valimus: 0.77,
    temperament: 0.86,
    kultuur: 0.92,
    juured: 0.96,
    portrait: "portraits/jaan-kross.jpg",
  },
  {
    id: "andrus-kivirahk",
    name: "Andrus Kivirähk",
    valimus: 0.76,
    temperament: 0.61,
    kultuur: 0.93,
    juured: 0.94,
    portrait: "portraits/andrus-kivirahk.jpg",
  },
  {
    id: "sofi-oksanen",
    name: "Sofi Oksanen",
    valimus: 0.69,
    temperament: 0.59,
    kultuur: 0.62,
    juured: 0.52,
    portrait: "portraits/sofi-oksanen.jpg",
  },
  {
    id: "tolstoy",
    name: "Leo Tolstoy",
    valimus: 0.53,
    temperament: 0.58,
    kultuur: 0.27,
    juured: 0.07,
    portrait: "portraits/tolstoy.jpg",
  },
  {
    id: "hemingway",
    name: "Ernest Hemingway",
    valimus: 0.39,
    temperament: 0.72,
    kultuur: 0.22,
    juured: 0.02,
    portrait: "portraits/hemingway.jpg",
    note: "nägi eestlasi sadamas",
  },
  {
    id: "kafka",
    name: "Franz Kafka",
    valimus: 0.38,
    temperament: 0.96,
    kultuur: 0.26,
    juured: 0.05,
    portrait: "portraits/kafka.jpg",
  },
  {
    id: "tanel-padar",
    name: "Tanel Padar",
    valimus: 0.86,
    temperament: 0.39,
    kultuur: 0.76,
    juured: 0.92,
    portrait: "portraits/tanel-padar.jpg",
  },
  {
    id: "christopher-nolan",
    name: "Christopher Nolan",
    valimus: 0.43,
    temperament: 0.77,
    kultuur: 0.47,
    juured: 0.01,
    portrait: "portraits/christopher-nolan.jpg",
  },
  {
    id: "robert-pattinson",
    name: "Robert Pattinson",
    valimus: 0.47,
    temperament: 0.73,
    kultuur: 0.42,
    juured: 0.02,
    portrait: "portraits/robert-pattinson.jpg",
    note: "Team Edward",
  },
  {
    id: "mads-mikkelsen",
    name: "Mads Mikkelsen",
    valimus: 0.58,
    temperament: 0.82,
    kultuur: 0.28,
    juured: 0.08,
    portrait: "portraits/mads-mikkelsen.jpg",
  },
  {
    id: "kaja-kallas",
    name: "Kaja Kallas",
    valimus: 0.99,
    temperament: 0.51,
    kultuur: 0.68,
    juured: 0.92,
    portrait: "portraits/kaja-kallas.jpg",
  },
  {
    id: "joe-biden",
    name: "Joe Biden",
    valimus: 0.35,
    temperament: 0.27,
    kultuur: 0.31,
    juured: 0.01,
    portrait: "portraits/joe-biden.jpg",
  },
  {
    id: "barack-obama",
    name: "Barack Obama",
    valimus: 0.09,
    temperament: 0.3,
    kultuur: 0.45,
    juured: 0.01,
    portrait: "portraits/barack-obama.jpg",
    note: "yes we can",
  },
  {
    id: "lotte",
    name: "Lotte",
    valimus: 0.03,
    temperament: 0.2,
    kultuur: 0.96,
    juured: 0.95,
    portrait: "portraits/lotte.jpg",
  },
  {
    id: "kalevipoeg",
    name: "Kalevipoeg",
    valimus: 0.65,
    temperament: 0.92,
    kultuur: 0.99,
    juured: 1,
    portrait: "portraits/kalevipoeg.jpg",
  },
  {
    id: "muumitroll",
    name: "Muumitroll",
    valimus: 0.01,
    temperament: 0.7,
    kultuur: 0.59,
    juured: 0.12,
    portrait: "portraits/muumitroll.jpg",
  },
  {
    id: "george-w-bush",
    name: "George W. Bush",
    valimus: 0.28,
    temperament: 0.28,
    kultuur: 0.46,
    juured: 0.01,
    portrait: "portraits/george-w-bush.jpg",
    note: "Welcome to NATO",
  },
  {
    id: "dave-benton",
    name: "Dave Benton",
    valimus: 0.11,
    temperament: 0.43,
    kultuur: 0.65,
    juured: 0.02,
    portrait: "portraits/dave-benton.jpg",
    note: "Palmid ja päike Aruubalt",
  },
  {
    id: "cheburashka",
    name: "Cheburashka",
    valimus: 0,
    temperament: 0.68,
    kultuur: 0.61,
    juured: 0.02,
    portrait: "portraits/cheburashka.jpg",
  },
  {
    id: "pipi-pikksukk",
    name: "Pipi Pikksukk",
    valimus: 0.41,
    temperament: 0.04,
    kultuur: 0.58,
    juured: 0.06,
    portrait: "portraits/pipi-pikksukk.jpg",
  },
  {
    id: "mart-avandi",
    name: "Märt Avandi",
    valimus: 0.91,
    temperament: 0.36,
    kultuur: 0.95,
    juured: 0.93,
    portrait: "portraits/mart-avandi.jpg",
  },
  {
    id: "ott-sepp",
    name: "Ott Sepp",
    valimus: 0.89,
    temperament: 0.35,
    kultuur: 0.91,
    juured: 0.93,
    portrait: "portraits/ott-sepp.jpg",
  },
  {
    id: "edgar-savisaar",
    name: "Edgar Savisaar",
    valimus: 0.68,
    temperament: 0.34,
    kultuur: 0.8,
    juured: 0.94,
    portrait: "portraits/edgar-savisaar.jpg",
  },
  {
    id: "anu-saagim",
    name: "Anu Saagim",
    valimus: 0.85,
    temperament: 0.07,
    kultuur: 0.78,
    juured: 0.88,
    portrait: "portraits/anu-saagim.jpg",
  },
  {
    id: "baruto",
    name: "Baruto",
    valimus: 0.66,
    temperament: 0.85,
    kultuur: 0.66,
    juured: 0.94,
    portrait: "portraits/baruto.jpg",
    note: "Väike-Maarja yokozuna",
  },
  {
    id: "nublu",
    name: "Nublu",
    valimus: 0.73,
    temperament: 0.76,
    kultuur: 0.82,
    juured: 0.91,
    portrait: "portraits/nublu.jpg",
    note: "öölaps",
  },
  {
    id: "5miinust",
    name: "5miinust",
    valimus: 0.72,
    temperament: 0.05,
    kultuur: 0.84,
    juured: 0.9,
    portrait: "portraits/5miinust.jpg",
    note: "narkootikumidest ei tea nad midagi",
  },
];
