// Display: SPF 50 / ei ütle tere tänaval / käib saunas.
// Scores from pairwise (2026-08-16). High = named pole. juured in data only.
export const people = [
  {
    id: "arvo-part",
    name: "Arvo Pärt",
    valimus: 0.93,
    temperament: 0.93,
    kultuur: 0.97,
    juured: 0.97,
    portrait: "portraits/arvo-part.jpg",
    note: "Isegi muusika oli vaikne",
  },
  {
    id: "lennart-meri",
    name: "Lennart Meri",
    valimus: 0.84,
    temperament: 0.49,
    kultuur: 0.89,
    juured: 0.95,
    portrait: "portraits/lennart-meri.jpg",
  },
  {
    id: "konstantin-pats",
    name: "Konstantin Päts",
    valimus: 0.82,
    temperament: 0.84,
    kultuur: 0.88,
    juured: 0.97,
    portrait: "portraits/konstantin-pats.jpg",
    note: "Vaikiv ajastu",
  },
  {
    id: "toomas-hendrik-ilves",
    name: "Toomas Hendrik Ilves",
    valimus: 0.7,
    temperament: 0.47,
    kultuur: 0.7,
    juured: 0.76,
    portrait: "portraits/toomas-hendrik-ilves.jpg",
    note: "Soome DJ",
  },
  {
    id: "kersti-kaljulaid",
    name: "Kersti Kaljulaid",
    valimus: 0.97,
    temperament: 0.5,
    kultuur: 0.69,
    juured: 0.93,
    portrait: "portraits/kersti-kaljulaid.jpg",
    note: "EU-CV",
  },
  {
    id: "kaja-kallas",
    name: "Kaja Kallas",
    valimus: 0.99,
    temperament: 0.51,
    kultuur: 0.68,
    juured: 0.92,
    portrait: "portraits/kaja-kallas.jpg",
  },
  {
    id: "edgar-savisaar",
    name: "Edgar Savisaar",
    valimus: 0.68,
    temperament: 0.34,
    kultuur: 0.8,
    juured: 0.94,
    portrait: "portraits/edgar-savisaar.jpg",
  },
  {
    id: "carmen-kass",
    name: "Carmen Kass",
    valimus: 1,
    temperament: 0.78,
    kultuur: 0.73,
    juured: 0.91,
    portrait: "portraits/carmen-kass.jpg",
    note: "Paide nägu, Milano valgus.",
  },
  {
    id: "ott-tanak",
    name: "Ott Tänak",
    valimus: 0.96,
    temperament: 0.99,
    kultuur: 0.77,
    juured: 0.94,
    portrait: "portraits/ott-tanak.jpg",
    note: "Sõnad otsas, gaas põhjas.",
  },
  {
    id: "tommy-cash",
    name: "Tommy Cash",
    valimus: 0.74,
    temperament: 0.42,
    kultuur: 0.81,
    juured: 0.76,
    portrait: "portraits/tommy-cash.jpg",
  },
  {
    id: "kerli",
    name: "Kerli",
    valimus: 0.95,
    temperament: 0.54,
    kultuur: 0.72,
    juured: 0.89,
    portrait: "portraits/kerli.jpg",
    note: "Metshaldjas",
  },
  {
    id: "nublu",
    name: "Nublu",
    valimus: 0.73,
    temperament: 0.76,
    kultuur: 0.82,
    juured: 0.91,
    portrait: "portraits/nublu.jpg",
    note: "öölaps",
  },
  {
    id: "mart-avandi",
    name: "Märt Avandi",
    valimus: 0.91,
    temperament: 0.36,
    kultuur: 0.95,
    juured: 0.93,
    portrait: "portraits/mart-avandi.jpg",
  },
  {
    id: "ott-sepp",
    name: "Ott Sepp",
    valimus: 0.89,
    temperament: 0.35,
    kultuur: 0.91,
    juured: 0.93,
    portrait: "portraits/ott-sepp.jpg",
  },
  {
    id: "anu-saagim",
    name: "Anu Saagim",
    valimus: 0.85,
    temperament: 0.07,
    kultuur: 0.78,
    juured: 0.88,
    portrait: "portraits/anu-saagim.jpg",
  },
  {
    id: "baruto",
    name: "Baruto",
    valimus: 0.66,
    temperament: 0.85,
    kultuur: 0.66,
    juured: 0.94,
    portrait: "portraits/baruto.jpg",
    note: "Väike-Maarja yokozuna",
  },
  {
    id: "tanel-padar",
    name: "Tanel Padar",
    valimus: 0.86,
    temperament: 0.39,
    kultuur: 0.76,
    juured: 0.92,
    portrait: "portraits/tanel-padar.jpg",
  },
  {
    id: "dave-benton",
    name: "Dave Benton",
    valimus: 0.11,
    temperament: 0.43,
    kultuur: 0.65,
    juured: 0.02,
    portrait: "portraits/dave-benton.jpg",
    note: "Palmid ja päike Aruubalt",
  },
  {
    id: "tammsaare",
    name: "A. H. Tammsaare",
    valimus: 0.78,
    temperament: 0.95,
    kultuur: 1,
    juured: 0.97,
    portrait: "portraits/tammsaare.jpg",
  },
  {
    id: "andrus-kivirahk",
    name: "Andrus Kivirähk",
    valimus: 0.76,
    temperament: 0.61,
    kultuur: 0.93,
    juured: 0.94,
    portrait: "portraits/andrus-kivirahk.jpg",
  },
  {
    id: "lotte",
    name: "Lotte",
    valimus: 0.03,
    temperament: 0.2,
    kultuur: 0.96,
    juured: 0.95,
    portrait: "portraits/lotte.jpg",
  },
  {
    id: "kalevipoeg",
    name: "Kalevipoeg",
    valimus: 0.65,
    temperament: 0.92,
    kultuur: 0.99,
    juured: 1,
    portrait: "portraits/kalevipoeg.jpg",
  },
  {
    id: "pipi-pikksukk",
    name: "Pipi Pikksukk",
    valimus: 0.41,
    temperament: 0.04,
    kultuur: 0.58,
    juured: 0.06,
    portrait: "portraits/pipi-pikksukk.jpg",
  },
  {
    id: "kimi-raikkonen",
    name: "Kimi Räikkönen",
    valimus: 0.64,
    temperament: 1,
    kultuur: 0.55,
    juured: 0.09,
    portrait: "portraits/kimi-raikkonen.jpg",
    note: "Bwoah",
  },
  {
    id: "elon-musk",
    name: "Elon Musk",
    valimus: 0.42,
    temperament: 0.53,
    kultuur: 0.04,
    juured: 0.03,
    portrait: "portraits/elon-musk.jpg",
    note: "Marsimees",
  },
  {
    id: "donald-trump",
    name: "Donald Trump",
    valimus: 0.36,
    temperament: 0,
    kultuur: 0.03,
    juured: 0.01,
    portrait: "portraits/donald-trump.jpg",
    note: "you're fired",
  },
  {
    id: "angela-merkel",
    name: "Angela Merkel",
    valimus: 0.57,
    temperament: 0.88,
    kultuur: 0.5,
    juured: 0.04,
    portrait: "portraits/angela-merkel.jpg",
    note: "wir schaffen das",
  },
  {
    id: "volodymyr-zelenskyy",
    name: "Volodymyr Zelenskyy",
    valimus: 0.27,
    temperament: 0.24,
    kultuur: 0.32,
    juured: 0.05,
    portrait: "portraits/volodymyr-zelenskyy.jpg",
    note: "Rahva teener",
  },
  {
    id: "barack-obama",
    name: "Barack Obama",
    valimus: 0.09,
    temperament: 0.3,
    kultuur: 0.45,
    juured: 0.01,
    portrait: "portraits/barack-obama.jpg",
    note: "yes we can",
  },
  {
    id: "george-w-bush",
    name: "George W. Bush",
    valimus: 0.28,
    temperament: 0.28,
    kultuur: 0.46,
    juured: 0.01,
    portrait: "portraits/george-w-bush.jpg",
    note: "Welcome to NATO",
  },
  {
    id: "xi-jinping",
    name: "Xi Jinping",
    valimus: 0.08,
    temperament: 0.8,
    kultuur: 0.01,
    juured: 0,
    portrait: "portraits/xi-jinping.jpg",
  },
  {
    id: "brad-pitt",
    name: "Brad Pitt",
    valimus: 0.51,
    temperament: 0.46,
    kultuur: 0.14,
    juured: 0.03,
    portrait: "portraits/brad-pitt.jpg",
  },
  {
    id: "christopher-nolan",
    name: "Christopher Nolan",
    valimus: 0.43,
    temperament: 0.77,
    kultuur: 0.47,
    juured: 0.01,
    portrait: "portraits/christopher-nolan.jpg",
  },
  {
    id: "jouluvana",
    name: "Jõuluvana",
    valimus: 0.5,
    temperament: 0.38,
    kultuur: 0.64,
    juured: 0.14,
    portrait: "portraits/jouluvana.jpg",
  },
  {
    id: "typical-american",
    name: "Keskmine Ameeriklane",
    valimus: 0.22,
    temperament: 0.14,
    kultuur: 0,
    juured: 0.01,
    portrait: "portraits/typical-american.jpg",
    note: "“Is Estonia in Eastern Europe?”",
  },
  {
    id: "latvian-neighbour",
    name: "Lätlane",
    valimus: 0.8,
    temperament: 0.66,
    kultuur: 0.57,
    juured: 0.33,
    portrait: "portraits/latvian-neighbour.jpg",
  },
];
